version: "3.8"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - DB_NAME=mydb
      - COLLECTION_NAME=items
    volumes:
      - ./app:/app
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: